In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
Train_data = pd.read_csv('Train.csv')

In [3]:
Test_data = pd.read_csv('Test.csv')

In [4]:
Train_data.head(10)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15        9.300          Low Fat         0.016047   
1           DRC01        5.920          Regular         0.019278   
2           FDN15       17.500          Low Fat         0.016760   
3           FDX07       19.200          Regular         0.000000   
4           NCD19        8.930          Low Fat         0.000000   
5           FDP36       10.395          Regular         0.000000   
6           FDO10       13.650          Regular         0.012741   
7           FDP10          NaN          Low Fat         0.127470   
8           FDH17       16.200          Regular         0.016687   
9           FDU28       19.200          Regular         0.094450   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   
5           Baking Goods   51.4008            OUT018   
6            Snack Foods   57.6588            OUT013   
7            Snack Foods  107.7622            OUT027   
8           Frozen Foods   96.9726            OUT045   
9           Frozen Foods  187.8214            OUT017   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   
5                       2009      Medium               Tier 3   
6                       1987        High               Tier 3   
7                       1985      Medium               Tier 3   
8                       2002         NaN               Tier 2   
9                       2007         NaN               Tier 2   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052  
5  Supermarket Type2           556.6088  
6  Supermarket Type1           343.5528  
7  Supermarket Type3          4022.7636  
8  Supermarket Type1          1076.5986  
9  Supermarket Type1          4710.5350

In [5]:
Train_data.shape

(8523, 12)

In [6]:
Train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [7]:
Train_data.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [8]:
Train_data.isnull().mean()

Item_Identifier              0.000000
Item_Weight                  0.171653
Item_Fat_Content             0.000000
Item_Visibility              0.000000
Item_Type                    0.000000
Item_MRP                     0.000000
Outlet_Identifier            0.000000
Outlet_Establishment_Year    0.000000
Outlet_Size                  0.282764
Outlet_Location_Type         0.000000
Outlet_Type                  0.000000
Item_Outlet_Sales            0.000000
dtype: float64

In [9]:
Train_data['Item_Weight'].value_counts()

Item_Weight
12.150    86
17.600    82
13.650    77
11.800    76
15.100    68
          ..
7.275      2
7.685      1
9.420      1
6.520      1
5.400      1
Name: count, Length: 415, dtype: int64

In [10]:
Train_data['Item_Weight'].max(),Train_data['Item_Weight'].min()

(21.35, 4.555)

In [11]:
Train_data['Item_Weight'].mean()

12.857645184135976

In [12]:
# Train_data['Item_Weight'].fillna(Train_data['Item_Weight'].mean(), inplace=True)

In [13]:
Train_data['Outlet_Size'].mode()

0    Medium
Name: Outlet_Size, dtype: object

In [14]:
#mode_of_Outlet_size = Train_data.pivot_table(values='Outlet_Size', columns='Outlet_Type', aggfunc=(lambda x: x.mode()[0]))

In [15]:
#print(mode_of_Outlet_size)

In [16]:
#miss_values = Train_data['Outlet_Size'].isnull()   

In [17]:
#Train_data.loc[miss_values, 'Outlet_Size'] = Train_data.loc[miss_values,'Outlet_Type'].apply(lambda x: mode_of_Outlet_size[x])

In [18]:
Train_data['Outlet_Size'].value_counts()

Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

In [19]:
Train_data['Outlet_Location_Type'].value_counts()

Outlet_Location_Type
Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: count, dtype: int64

In [20]:
Train_data['Outlet_Type'].value_counts()

Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64

In [21]:
Train_data['Item_Outlet_Sales'].value_counts()

Item_Outlet_Sales
958.7520     17
1342.2528    16
703.0848     15
1845.5976    15
1278.3360    14
             ..
4124.6310     1
6622.7126     1
1614.5650     1
5602.7070     1
2778.3834     1
Name: count, Length: 3493, dtype: int64

In [22]:
Train_data['Outlet_Size'][Train_data['Outlet_Size'].isnull()] = Train_data['Outlet_Size'].dropna().sample(Train_data['Outlet_Size'].isnull().sum()).values

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9996\228243936.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Train_data['Outlet_Size'][Train_data['Outlet_Size'].isnull()] = Train_data['Outlet_Size'].dropna().sample(Train_data['Outlet_Size'].isnull().sum()).values


In [23]:
Train_data['Item_Weight'][Train_data['Item_Weight'].isnull()] = Train_data['Item_Weight'].dropna().sample(Train_data['Item_Weight'].isnull().sum()).values

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9996\3833671201.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Train_data['Item_Weight'][Train_data['Item_Weight'].isnull()] = Train_data['Item_Weight'].dropna().sample(Train_data['Item_Weight'].isnull().sum()).values


In [24]:
Train_data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [25]:
Train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                8523 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [26]:
Train_data['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: count, dtype: int64

In [27]:
Train_data.replace({'Item_Fat_Content': {'low fat':'Low Fat','LF':'Low Fat', 'reg':'Regular'}}, inplace=True)

In [28]:
Train_data['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    5517
Regular    3006
Name: count, dtype: int64

In [29]:
Train_data['Outlet_Size'].value_counts()

Outlet_Size
Medium    3905
Small     3317
High      1301
Name: count, dtype: int64

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

transformer = ColumnTransformer(transformers=[
    ('tnf2',OrdinalEncoder(categories=[['Low Fat','Regular'],['Small','Medium','High'],['Tier 3','Tier 2','Tier 1'],['Grocery Store', 'Supermarket Type1','Supermarket Type2','Supermarket Type3']]),['Item_Fat_Content','Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type',])],remainder='passthrough')
    

In [31]:
Train_data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [32]:
X = Train_data.drop(columns=['Item_Outlet_Sales','Item_Identifier','Outlet_Identifier','Item_Type'])
Y = Train_data['Item_Outlet_Sales']

In [33]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Weight                8523 non-null   float64
 1   Item_Fat_Content           8523 non-null   object 
 2   Item_Visibility            8523 non-null   float64
 3   Item_MRP                   8523 non-null   float64
 4   Outlet_Establishment_Year  8523 non-null   int64  
 5   Outlet_Size                8523 non-null   object 
 6   Outlet_Location_Type       8523 non-null   object 
 7   Outlet_Type                8523 non-null   object 
dtypes: float64(3), int64(1), object(4)
memory usage: 532.8+ KB


In [34]:
X=transformer.fit_transform(X)

In [35]:
X.shape

(8523, 8)

In [36]:
Y.head(5)

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y.values, test_size=0.2, random_state=2)

In [38]:
# from sklearn.impute import KNNImputer
# knn= KNNImputer(n_neighbors=5,weights='uniform')
# X_train=knn.fit_transform(X_train)
# X_test=knn.transform(X_test)

In [39]:
# X_train=transformer.fit_transform(X_train)
# X_test=transformer.transform(X_test)

In [40]:
X.dtype

dtype('float64')

In [41]:
print(X.shape, X_train.shape, X_test.shape)

(8523, 8) (6818, 8) (1705, 8)


In [42]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
Y_train_scaled = sc_y.fit_transform(Y_train.reshape(-1,1))

In [43]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [44]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)

In [45]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.48872444368590706

In [46]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, Y_train)

LinearRegression()

In [47]:
Y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.5633963508590644

In [48]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, Y_train)

SVR()

In [49]:
y_pred = (regressor.predict((X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1781.64 1544.66]
 [1802.98 6405.  ]
 [1783.2  1070.61]
 ...
 [1793.75 1551.98]
 [1804.2  3068.01]
 [1800.71 5480.87]]


In [50]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

-0.05971828171531324

In [51]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train_scaled, Y_train_scaled)

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [52]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[2083.15 1544.66]
 [3677.26 6405.  ]
 [1324.66 1070.61]
 ...
 [2562.68 1551.98]
 [3274.16 3068.01]
 [3174.12 5480.87]]


In [53]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.5776293758274638

In [54]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=0)

In [55]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[2450.14 1544.66]
 [1231.73 6405.  ]
 [2498.08 1070.61]
 ...
 [2586.63 1551.98]
 [3616.63 3068.01]
 [2303.67 5480.87]]


In [56]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.20659094418505874

In [57]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, Y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [58]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[2404.47 1544.66]
 [2579.11 6405.  ]
 [1544.12 1070.61]
 ...
 [3140.98 1551.98]
 [3135.85 3068.01]
 [3258.43 5480.87]]


In [59]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.5253598119384331

In [60]:
from xgboost import XGBRegressor

In [61]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [62]:
from xgboost import XGBRegressor

In [63]:
regressor = XGBRegressor()
regressor.fit(X_train, Y_train)
# prediction on training data
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))
r2_score(Y_test, y_pred)

[[2687.2  1544.66]
 [1718.32 6405.  ]
 [1618.01 1070.61]
 ...
 [2534.37 1551.98]
 [1974.66 3068.01]
 [3460.54 5480.87]]


0.5237017242936033